- hosts: 192.168.211.16,192.168.211.17,192.168.211.18
  gather_facts: false
  connection: local
  vars:
    switch_id: 0
    set_config:
      id: 1
      method: Switch.SetConfig
      params:
        id: "{{ switch_id }}"
        config:
          initial_state: "restore_last"

  tasks:

    # Official documentation:
    # https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Switch#configuration

    - name: Get Shelly config
      ansible.builtin.uri:
        method: get
        url: "http://{{ inventory_hostname }}/rpc/Switch.GetConfig?id={{ switch_id }}"
      delegate_to: localhost
      register: switchconfig
      changed_when: false

    #- debug: var=set_config
    #- debug: msg="{{ set_config | to_json }}"

    - name: Show current value
      debug: var=switchconfig.json.initial_state

    - name: Set initial state
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/rpc"
        method: POST
        body: "{{ set_config | to_json }}"
        status_code: 200
      delegate_to: localhost
      when: switchconfig.json.initial_state != set_config.params.config.initial_state
      register: response
      changed_when: true
      failed_when: response.json.error is defined or response.status != 200

    - name: Show response
      debug: var=response
      when: response is not skipped