- name: Update pihole
  hosts: pihole*.lan
  serial: 1
  vars:
    dnstest:
      - { host: 'archlinux.org',   ip: '209.126.35.79' }
      - { host: 'flurry.com',      ip: '0.0.0.0' }
      - { host: 'doubleclick.net', ip: '0.0.0.0' }

  tasks:

  - name: Check for updates
    shell: "pihole -up --check-only"
    register: checkresult
    changed_when: false

  - name: Debug
    debug: msg="{{ checkresult }}"

  - when: "'Everything is up to date!' not in checkresult.stdout"
    block:
      - name: Fetch DNS before update
        shell: "dig +short @localhost {{ item.host }}"
        register: digresult
        changed_when: false
        loop: "{{ dnstest }}"

      - name: Debug
        debug: msg="{{ digresult }}"

      - name: Fail if ip mismatch
        fail:
          msg: "IP mismatch. dig returned '{{ item.stdout }}', expected '{{ item.item.ip }}'"
        when: "item.stdout != item.item.ip"
        loop: "{{ digresult.results }}"

      - name: Update pihole
        shell: "pihole -up"
        register: updateresult
        changed_when: "'Update Complete!' in updateresult.stdout"

      - name: Debug
        debug: msg="{{ updateresult }}"

      - name: Fetch DNS after update
        shell: "dig +short @localhost {{ item.host }}"
        register: digresult
        changed_when: false
        loop: "{{ dnstest }}"

      - name: Fail if ip mismatch
        fail:
          msg: "IP mismatch. dig returned '{{ item.stdout }}', expected '{{ item.item.ip }}'"
        when: "item.stdout != item.item.ip"
        loop: "{{ digresult.results }}"