- name: Update tasmota firmware of Delock device
  #hosts: delocks
  hosts: 192.168.209.3
  gather_facts: false
  vars:
    update_url: "http://ota.tasmota.com/tasmota/release-{{update_to}}/tasmota-DE.bin.gz"
    afterupdate_version: "{{update_to}}(tasmota)"
    # Ab 14.0: 14.0.0(release-tasmota)
    afterupdate_version_beginningv14: "{{update_to}}(release-tasmota)"
    use_update_set: 14
    update_sets:
      0:
        current_version: "7.2.0(basic)"
        update_to: "8.5.1"
      1:
        current_version: "8.5.1(tasmota)"
        update_to: "9.1.0"
      2:
        current_version: "9.1.0(tasmota)"
        update_to: "9.3.1"
      3:
        current_version: "9.3.1(tasmota)"
        update_to: "12.0.2"
      4:
        current_version: "12.0.2(tasmota)"
        update_to: "12.1.1"
      5:
        current_version: "12.1.1(tasmota)"
        update_to: "12.2.0"
      6:
        current_version: "12.2.0(tasmota)"
        update_to: "12.3.1"
      7:
        current_version: "12.3.1(tasmota)"
        update_to: "12.4.0"
      8:
        current_version: "12.4.0(tasmota)"
        update_to: "12.5.0"
      9:
        current_version: "12.5.0(tasmota)"
        update_to: "13.0.0"
      10:
        current_version: "13.0.0(tasmota)"
        update_to: "13.1.0"
      11:
        current_version: "13.1.0(tasmota)"
        update_to: "13.2.0"
      12:
        current_version: "13.2.0(tasmota)"
        update_to: "13.4.0"
      13:
        current_version: "13.3.0(tasmota)"
        update_to: "13.4.0"
      14:
        current_version: "13.4.0(tasmota)"
        update_to: "14.0.0"
      # Update von 13.2.0 auf 13.4.0 direkt ging ohne Probleme
      #
      #afterupdate_version: "12.2.0(tasmota)"
      #update_url: "http://ota.tasmota.com/tasmota/release-12.2.0/tasmota-DE.bin.gz"
      #update_url: "http%3A%2F%2Fota.tasmota.com%2Ftasmota%2Frelease-12.2.0%2Ftasmota-DE.bin.gz"

  tasks:
    - set_fact:
        previous_version: "{{ update_sets[ use_update_set ].current_version }}"
        update_to: "{{ update_sets[ use_update_set ].update_to }}"
    - debug:
        var: previous_version
    - debug:
        var: update_to

    - name: Retrieve JSON
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/cm?cmnd=status%202"
      register: jsonout
      delegate_to: localhost

    - debug:
        var: jsonout

    - set_fact:
        firmware_version: "{{ jsonout.json.StatusFWR.Version }}"

    - debug:
        var: firmware_version

    - name: End the play for a device when already at new version
      ansible.builtin.meta: end_host
      when:
      - firmware_version == afterupdate_version

    - block:

        - name: Start firmware update
          ansible.builtin.uri:
            url: "http://{{ inventory_hostname }}/u1?o={{ update_url | urlencode }}"
            method: GET
            headers:
              Referer: "http://{{ inventory_hostname }}/up?"
          delegate_to: localhost
          changed_when: uriupdate.status == 200
          register: uriupdate

        - debug:
            var: uriupdate

        - name: Pause
          ansible.builtin.pause:
            seconds: 20

        - name: Retrieve JSON
          ansible.builtin.uri:
            url: "http://{{ inventory_hostname }}/cm?cmnd=status%202"
          register: jsonout_afterupdate
          delegate_to: localhost
          until: (jsonout_afterupdate.failed is false) and (jsonout_afterupdate.status == 200) and (jsonout_afterupdate.json.StatusFWR.Version is defined) and ( (jsonout_afterupdate.json.StatusFWR.Version == afterupdate_version) or (jsonout_afterupdate.json.StatusFWR.Version == afterupdate_version_beginningv14) )
          retries: 8
          delay: 10

        - debug: var=jsonout_afterupdate

        - assert:
            that:
              - 'jsonout_afterupdate.json.StatusFWR.Version == afterupdate_version  or  jsonout_afterupdate.json.StatusFWR.Version == afterupdate_version_beginningv14'

      when: previous_version == firmware_version
